version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    expose:
      - "2181"
    networks:
        adsnet:
            aliases:
              - zookeeper  
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    expose:
      - "9092"
      - "9094"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:      
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://172.16.1.236:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        adsnet:
            aliases:
              - kafka  
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9005:9000"
    expose:
      - "9005"
    links:
      - zookeeper:zk
      - kafka:kafka
    environment:
      ZK_HOSTS: zookeeper:2181      
    networks:
        adsnet:
            aliases:
                - kafka-manager  

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  adsnet:
    external:
       name: adsnet
